name: Publish docker image to SaveMyBank registry

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: gym-stats

jobs:
  push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg DATABASE_URL=postgresql://postgres:postgres@localhost:5432/gym-stats

      - uses: docker/login-action@v1
        with:
          registry: registry.savemybank.lt
          username: save-my-bank
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image to SaveMyBank Container Registry
        run: |
          IMAGE_ID=registry.savemybank.lt/$IMAGE_NAME

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
